### PR TITLE
Add menu for browser

### PR DESCRIPTION
**Pull request by sogaiu**
How about a menu for the browser?

Here is a sketch / draft of a menu for the browser:

```
      '("SesmanBrowser"
        ["Next section / row" sesman-browser-vertical-next]
        ["Previous section / row" sesman-browser-vertical-prev]
        "--"
        ["Next button" sesman-browser-forward]
        ["Previous button" sesman-browser-backward]
        "--"
        ["Next session" sesman-browser-session-next]
        ["Previous session" sesman-browser-session-prev]
        "--"
        ["Goto buffer" sesman-goto]
        ["Show buffer" sesman-show]
        "--"
        ["Toggle sort" sesman-browser-toggle-sort]
        "--"
        ["Link with Buffer" sesman-browser-link-with-buffer]
        ["Link with Directory" sesman-browser-link-with-directory]
        ["Link with Project" sesman-browser-link-with-project]
        "--"
        ["Unlink" sesman-browser-unlink]
        "--"
        ["Refresh View" revert-buffer]))
```

### CODE REVIEW

**Comment by vspinu** [comment]
Looks good. But I would just keep "row" instead of "section/row". Also "Toggle sort" can be just before "Refresh View" in the same section.  I think there are too many sections/separators. Maybe put "Unlink" with other "Link"s, and put all buffer navigation commands in one section? Something like this:

```
'("SesmanBrowser"
        ["Next row" sesman-browser-vertical-next]
        ["Previous row" sesman-browser-vertical-prev]
        ["Next button" sesman-browser-forward]
        ["Previous button" sesman-browser-backward]
        ["Next session" sesman-browser-session-next]
        ["Previous session" sesman-browser-session-prev]
        "--"
        ["Goto buffer" sesman-goto]
        ["Show buffer" sesman-show]
        "--"
        ["Link with Buffer" sesman-browser-link-with-buffer]
        ["Link with Directory" sesman-browser-link-with-directory]
        ["Link with Project" sesman-browser-link-with-project]
        ["Unlink" sesman-browser-unlink]
        "--"
        ["Toggle sort" sesman-browser-toggle-sort]
        ["Refresh View" revert-buffer]))
```
Also, once the pointer is on the sesman object, session management commands are available. It might be worth adding those as well. But it's a bit tricky because it's a local map.

**Comment by sogaiu** [comment]
That looks fine to me -- I just noticed that the Sesman menu has a separator between the linking items and unlink.  Does that difference stand out at all to you?  The grouping in SesmanBrowser does seem natural in that context.

Also, I thought it might be nice to advertise the existence of the browser through the Sesman menu.  How does that idea seem to you?

Regarding:

> Also, once the pointer is on the sesman object, session management commands are available. It might be worth adding those as well. But it's a bit tricky because it's a local map.

I'm not sure I understand.  Is this idea similar to how you used :active for the Sesman menu?  So under certain conditions some menu items would be active while under other conditions they would be greyed out?  Please elaborate :)

**Comment by vspinu** [comment]
> Does that difference stand out at all to you? The grouping in SesmanBrowser does seem natural in that context.

I don't have a preference here. If separating "unlink" from links feels natural to you please do. It probably felt right back then when I designed it. 

> Also, I thought it might be nice to advertise the existence of the browser through the Sesman menu. How does that idea seem to you?

I am surprised it's not there already :)

> I'm not sure I understand. Is this idea similar to how you used :active for the Sesman menu? 

Nevermind. I meant that the objects (REPL buffers) have local maps on them, and those local maps are decided by the backends themselves in `sesman-session-info`'s `:map` property. I just thought that the backend might want to put some items in the sesman's menu. Now I see that it's a far fetched and not worthy idea.

**Comment by sogaiu** [comment]
Thanks for the clarifications and feedback.

I've updated the menu to reflect your original idea.  A lone unlink item somehow doesn't seem right in this context.  How does the diff look now?

Should I make a separate PR for adding the browser to the Sesman menu?

**Comment by vspinu** [comment]
> Should I make a separate PR for adding the browser to the Sesman menu?

No need. Just push a separate commit here. Thanks.

**Comment by sogaiu** [comment]
After adding the Browser item, the lone Unlink item looked a bit odd, so I tried grouping it along with the Link items.

Also, I thought may be it's better for the Browser item to be inactive if there are no relevant sessions.

What do you think?

**Comment by vspinu** [comment]
Let's keep it active for now. `sesman-browser` would work, so the menu should be working as well. In the future there should be an option to to view sessions from all systems in the browser on a prefix or something. Even if there are no relevant sessions for the current system.

**Comment by vspinu** [comment]
Looks good. Thanks!

**Comment by sogaiu** [comment]
Thanks!

**Pull request merged**
